[theme]
primaryColor = "#0077b6"
backgroundColor = "#212529"
secondaryBackgroundColor = "#2c2f33"
textColor = "#ffffff"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
magicEnabled = true

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"