# Example secrets configuration file
# Copy this file to .streamlit/secrets.toml and add your API keys

# Required: Gemini API Key for AI functionality
GEMINI_API_KEY = "your_gemini_api_key_here"

# Optional: Weather API Key for weather information
# The app will work without this, but weather features will be limited
WEATHER_API_KEY = "your_weather_api_key_here"

# App configuration
ENABLE_MOCK_API = false  # Set to true to use mock data instead of real APIs